<a href="https://colab.research.google.com/github/Elisakova/github_welcom/blob/main/Numpy_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi")
      

hi


In [ ]:
import numpy as np
arr1=np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#c
arr2=np.ones(10)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Создать массив из 10 пятерок
print(np.full(10,5))

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Создать массив из целых чисел от 10 до 50
print(np.arange(10,51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#Создать массив из целых чисел от 10 до 50
print(np.arange(10,51,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#Создать матрицу 3х3 с числами от 0 до 8
arr=np.arange(0,9)
print(arr)
matrix=arr.reshape((3,3))
print(matrix)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Создать единичную матрицу 3x3
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Используйте NumPy для генерации случайного числа от 0 до 1
a=np.random.randint(0, 1)
print(a)

0


In [ ]:
#Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
a=np.random.randn(25)
print(a)

[ 0.53933188  0.55739996 -0.24583903  1.81328862 -1.01809008  0.07677036
  0.52541525  1.80635571 -1.12906763 -2.26002054 -0.06537615  0.68251555
  0.2650284  -1.04430507 -0.26655041 -1.17062408  0.22129653  1.20684605
 -0.2249262  -1.73197359 -1.19145941 -0.30203267 -1.6058194  -0.42356304
  0.96530006]


In [ ]:
#Создайте следующую матрицу используя функции библиотеки NumPy:

arr1=np.arange(0.01,1.01,0.01)

print(arr1.reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
 #I ) это наша стартовая матрица 
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('__________________')
print(mat[2:,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
__________________
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
#m.Написать код обращения к элементу который вернет значение  20
print(mat[3, 4])

20


In [ ]:
#n.Написать код к стартовой матрице задачи l 
arr1=(mat[0:3,1])
arr2=np.reshape(arr1,(3,1))
print(arr2)

[[ 2]
 [ 7]
 [12]]


In [ ]:
#o.Написать код к стартовой матрице задачи l 
print(mat[4:])


[[21 22 23 24 25]]


In [ ]:
#p.Написать код к стартовой матрице задачи l
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#q.Получить сумму всех значений в стартовой матрице mat
x=(np.sum(mat))
print(f'сумма всех значений в матрице - {x}')

сумма всех значений в матрице - 325


In [ ]:
#Получить стандартное отклонение в стартовой матрице mat
x=np.std(mat)
print(f'стандартное отклонение в матрице равно : {x}')

стандартное отклонение в матрице равно : 7.211102550927978


In [ ]:
#s.Получить сумму значений в колонках в стартовой матрице
x=mat.sum(axis=0)
y=mat.sum(axis=1)
print(f'сумма значений в столбцах = {x}')
print(f'свмма значений в строках = {y}')

сумма значений в столбцах = [55 60 65 70 75]
свмма значений в строках = [ 15  40  65  90 115]
